routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Library\RouteLoader;

// Load the main app routes
RouteLoader::loadRoutesFromDirectory(base_path('routes/app'));
// Load the admin routes
RouteLoader::loadRoutesFromDirectory(base_path('routes/admin'));

// Route::get('/debug-sentry', function () {
//     throw new Exception('My first Sentry error!');
// });

app/Models/Weapon.php
<?php

namespace App\Models;

class Weapon extends ResourceIsolatedModel {

    const WEAPON_STASH_TYPE_SHOOTER     = 1;
    const WEAPON_STASH_TYPE_COLLECTOR   = 2;
    const WEAPON_STASH_TYPE_HUNTER      = 3;

    const WEAPON_STASHES = [
        self::WEAPON_STASH_TYPE_SHOOTER => 'Atirador',
        self::WEAPON_STASH_TYPE_COLLECTOR => 'Colecionador',
        self::WEAPON_STASH_TYPE_HUNTER => 'Caçador',
    ];

    const WEAPON_STATUS_ACCEPTED                        = 'accepted';
    const WEAPON_STATUS_NOT_ACCEPTED                    = 'not_accepted';
    const WEAPON_STATUS_TEMPORARILY_NOT_ACCEPTED        = 'temporarily_not_accepted';
    const WEAPON_STATUS_PENDENCIES                      = 'pendencies';

    const WEAPON_STATUSES = [
        self::WEAPON_STATUS_ACCEPTED                    => 'Deferido',
        self::WEAPON_STATUS_NOT_ACCEPTED                => 'Indeferido',
        self::WEAPON_STATUS_TEMPORARILY_NOT_ACCEPTED    => 'Temporariamente Indeferido',
        self::WEAPON_STATUS_PENDENCIES                  => 'Exigências',
    ];



    const MASK_MAPPING = [
        'WEAPON_RECEIPT_NUMBER'                 => 'receipt_number',
        'WEAPON_TYPE'                           => 'type',
        'WEAPON_BRAND'                          => 'brand',
        'WEAPON_CALIBER'                        => 'caliber',
        'WEAPON_SERIAL_NUMBER'                  => 'serial_number',
        'WEAPON_MODEL'                          => 'model',
        'WEAPON_STASH'                          => 'stash',
        'WEAPON_DOCS_ISSUED_AT'                 => 'docs_issued_at',
        'WEAPON_SIGMA_NUMBER'                   => 'sigma_number',
        'WEAPON_STATUS'                         => 'status',
        'WEAPON_TRANSIT_PERMISSION_NUMBER'      => 'transit_permission_number',
        'WEAPON_TRANSIT_PERMISSION_EXPIRY_DATE' => 'transit_permission_expiry_date',
//        'WEAPON_CUSTOMER_ID'                    => 'customer_id',
    ];

    protected $fillable = [
        'receipt_number','type', 'brand','caliber','serial_number','model','stash',
        'sigma_number','status','transit_permission_number',
        'customer_id'
    ];

    protected $dates = [
        'docs_issued_at',
        'transit_permission_expiry_date',
    ];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public static function rules()
    {
        return [
            'receipt_number'                    => 'required',
            'type'                              => 'required',
            'brand'                             => 'required',
            'caliber'                           => 'required',
            'serial_number'                     => 'required',
            'model'                             => 'required',
            'stash'                             => 'required',
            'transit_permission_expiry_date'    => 'nullable|date',
        ];
    }

    public static function validationMessages()
    {
        return [
            'receipt_number.required'                => 'O numero da nota fiscal é obrigatório',
            'type.required'                          => 'O tipo da arma é obrigatório',
            'brand.required'                         => 'A marca da arma é obrigatória',
            'caliber.required'                       => 'O calibre da arma é obrigatório',
            'serial_number.required'                 => 'O número de série da arma é obrigatório',
            'model.required'                         => 'O modelo da arma é obrigatório',
            'stash.required'                         => 'O acervo da arma é obrigatório',
            'transit_permission_expiry_date.date'    => 'A data de validade da guia de trânsito é inválida',
        ];
    }

    // Override no método delete padrão
    public function delete()
    {
        // Checar se pode deletar
        //if($this->customers()->count() > 0){
            // Se não puder, throw no erro
            //throw new CannotDeleteException('Não é possível excluir um clube com clientes vinculados.');
        //}
        // Retornar ok se der bom
        return parent::delete();
    }

    /**
     * @return string
     */
    public function getName()
    {
        return sprintf('%s %s - %s', $this->brand, $this->model, $this->caliber);
    }

    /**
     * Mutator
     * @return string
     */
    public function getNameAttribute()
    {
        return $this->getName();
    }


    public function getMaskMapping()
    {
        return self::MASK_MAPPING;
    }


    /**
     * @return string
     * @throws \Exception
     */
    public function getStash()
    {
        try {
            return self::WEAPON_STASHES[$this->stash];
        }catch(\Exception $e){
            return 'Indefinido';
        }
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function getStatus()
    {
        try {
            return self::WEAPON_STATUSES[$this->status];
        }catch(\Exception $e){
            return 'Indefinido';
        }
    }


    /**
     * Essa function vai dar uma cor de texto para cada status da arma
     * @return null|string
     */
    public function getStatusClass()
    {
        switch($this->status){
            case self::WEAPON_STATUS_ACCEPTED:
                return 'text-success';
            case self::WEAPON_STATUS_NOT_ACCEPTED:
            case self::WEAPON_STATUS_TEMPORARILY_NOT_ACCEPTED:
                return 'text-danger';
            case self::WEAPON_STATUS_PENDENCIES:
                return 'text-warning';
            default:
                return null;
        }
    }


    public function getDocsIssuedAt()
    {
        return $this->docs_issued_at->formatLocalized('%d/%m/%Y');
    }

    public function getTransitPermissionExpiryDate()
    {
        return $this->transit_permission_expiry_date->formatLocalized('%d/%m/%Y');
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layout', [
    'page_title' => 'Admin Dashboard'
])

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                    <img class="img-responsive float-left mr-2" style="max-width: 90px" src="{{asset('assets/img/brasao.jpeg')}}" alt="">
                    <h3 class="mt-4">Olá, {{auth()->user()->name}}!</h3>
                    <p class="mb-0">Bem vindo ao Painel Admin docGun!</p>
                </div>
            </div>
            <div class="row" style="margin-top: 50px; min-height: 250px;">
                {{-- Gráfico de empresas nos últimos 12 meses --}}
                <div class="col-md-12">
                    <h5>Total de empresas nos útimos 12 meses</h5>
                    <div id="companies-chart"></div>
                </div>
            </div>
            <div class="row mt-4">

                <div class="col-md-12">
                    <hr />
                    <h6>
                        Total de empresas: {{$totalCompanies}} |
                        Total de planos gratis: {{$freeSubscriptions}} |
                        Total de planos pagos: {{$paidSubscriptions}}
                    </h6>
                    <hr />
                </div>

                {{--  Últimas 05 empresas cadastradas --}}
                <div class="col-md-4">
                    <h5>Últimas empresas cadastradas</h5>
                    <table class="table table-bordered table-hover">
                        <tr>
                            <th>Nome</th>
                            <th>Data</th>
                        </tr>
                        @if(count($latestCompanies))
                            @foreach($latestCompanies as $compamy)
                                <tr>
                                    <td>
                                        <a href="nope.html">
                                            {{$compamy->name}}
                                        </a>
                                    </td>
                                    <td>
                                        {{$compamy->created_at->formatLocalized('%d/%m/%Y')}}
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="2">Nenhuma empresa encontrada.</td>
                            </tr>
                        @endif
                    </table>
                </div>
                {{--  Teste grátis encerrando nos próximos 5 dias --}}
                <div class="col-md-4">
                    <h5>Teste grátis encerrando nos próximos 5 dias</h5>
                    <table class="table table-bordered table-hover">
                        <tr>
                            <th>Nome</th>
                            <th>Data</th>
                        </tr>
                        @if(count($trialExpiringSubscriptions))
                            @foreach($trialExpiringSubscriptions as $subscription)
                                <tr>
                                    <td>
                                        <a href="nope.html">
                                            {{$subscription->company->name}}
                                        </a>
                                    </td>
                                    <td>
                                        {{$subscription->terminate_at->formatLocalized('%d/%m/%Y')}}
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="2">Nenhuma assinatura encontrada.</td>
                            </tr>
                        @endif
                    </table>
                </div>
                {{--  Subscriptions pagas mais recentes --}}
                <div class="col-md-4">
                    <h5>Últimas assinaturas pagas</h5>
                    <table class="table table-bordered table-hover">
                        <tr>
                            <th>Nome</th>
                            <th>Data</th>
                            <th>Status</th>
                        </tr>
                        @if(count($newestPaidSubscriptions))
                            @foreach($newestPaidSubscriptions as $subscription)
                                <tr>
                                    <td>
                                        <a href="nope.html">
                                            {{$subscription->company->name}}
                                        </a>
                                    </td>
                                    <td>
                                        {{$subscription->terminate_at->formatLocalized('%d/%m/%Y')}}
                                    </td>
                                    <td>
                                        {{$subscription->status}}
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="3">Nenhuma assinatura encontrada.</td>
                            </tr>
                        @endif
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop


@section('extras_js')
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        google.charts.load('current', {'packages':['bar']});
        google.charts.setOnLoadCallback(drawChart);


        function drawChart() {

            // Set chart options
            let options = {
                legend: {
                    position: 'none',
                },
                hAxis: {
                    title: '',
                },
                series: {
                    0: {color: '#2F5B38'},
                }
            };

            // ===================== Customers chart
            let array_data = JSON.parse('{!! json_encode($companiesDatatable) !!}');
            array_data.unshift(['Mês', 'Total']);
            let data = new google.visualization.arrayToDataTable(array_data, false);

            // Instantiate and draw our chart, passing in some options.
            let chart = new google.charts.Bar(document.getElementById('companies-chart'));
            chart.draw(data, google.charts.Bar.convertOptions(options));

        }
    </script>
@stop

resources/views/admin/layout.blade.php
@extends('base', [
    'page_title' => isset($page_title) ? $page_title : null,
    'body_class' => 'dotted app header-fixed sidebar-fixed sidebar-compact'
])
@section('page')
    <header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
        <a class="navbar-brand text-center" href="{{route('get_dashboard')}}">
            <img class="logomarca" src="{{asset('assets/img/docgun-logo.png')}}" alt="">
        </a>

        <ul class="nav navbar-nav ml-auto" style="margin-right: 50px;">

            <li class="nav-item dropdown" >
                <a class="nav-link nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    {{--<img class="img-avatar" src="img/avatars/6.jpg">--}}
                    Olá, {{auth()->user()->firstName()}}
                    <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{route('get_dashboard')}}">
                        <i class="fa fa-user"></i> Painel do Usuário
                    </a>
                    <a class="dropdown-item" href="{{route('get_logout')}}">
                        <i class="fa fa-sign-out"></i> Sair
                    </a>
                </div>
            </li>
        </ul>

    </header>
    <div class="app-body">
    @include('admin.partials._sidebar')

    <!-- Main content -->
        <main class="main">

            <div class="container-fluid">
                <div class="animated fadeIn">

                    {{--Mensagens em flash--}}
                    @include('partials._flash')

                    {{--Mensagens em erro de forms--}}
                    @include('partials._errors')

                    {{--Conteúdo da página--}}
                    @yield('content')
                </div>

            </div>
            <!-- /.conainer-fluid -->
        </main>
    </div>
    <footer class="app-footer">
        <a href="https://monazite.com.br" target="_blank"><span style="color: #d2a147">mona</span><span style="color: #0a0a0a">zite</span></a> © {{\Carbon\Carbon::now()->year}} docGun -
    </footer>
@stop